nama = str(input("Masukkan nama Anda : "))
pelajaran = str(input("Masukkan nama matakuliah : "))
grup = str(input("Masukkan grup Anda : "))
print("Haloo!", nama*2)
print("Anda tergabung dalam kelas", pelajaran, "pada grup", grup)