name=str(input("STATE YOUR NAME: "))
print("="*110)
print("")
print("<"*10, "Adventure of", name, ">"*10)
print("")
print("Welcome to the Adventure of", name, "!")
print("")
print("Are you a Male/Female ? [M/F]")
gender=str(input(">> "))
print("")
print("")
print("")

print("One day, A young adventurer named", name)
print("spawned in a peacefull Village of Orion")
print(name, "walked out of village and see a slime jumping around.")
print("")
print("picked up a... (Sword/Bow)")
alat=str(input(">> "))
print("and attack the slime.\nthe slime get sliced and died. adventurer gain a level.")
print("")

print(name, "The Adventurer, then run towards a chest that glows from the inside\nPICK ONE!\nOPEN/WALK")
pilih=str(input(">> "))
print("")

print("The Adventurer Finds a Gold and brings it Home to the Village.")
print("")

print("as the adventure walks, he started to feel more and more tired.\nTake a [Break] / Keep [Walk]ing")
cape=str(input(">> "))
print("")

print(name, "Arrived at the village and see RTX 3090 Ti on sale\nWith the price of 1 gold")
beli=str(input("[BUY] / [PASS]>> "))
print("Congratulation! you got your dream stuff!\nNow you can play Minecraft with Raytracing FOREVER !")
print("")
print("And live Happily ever After!~~")